version: '3.8'

services:
  mongodb:
    image: mongo:6.0.18
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ai2
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongodb:27017/ai2
      JWT_SECRET: my-super-secret-jwt-key-which-should-be-long
    depends_on:
      - mongodb

volumes:
  mongo_data: 